### ISSUE TITLE
'member of dojos' is incorrect..

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#620] opened 2015-09-11 14:56 UTC
should be only two dojos here...

![screen shot 2015-09-11 at 15 55 01](https://cloud.githubusercontent.com/assets/602445/9817903/9a3ade06-589d-11e5-89ef-0e2db11fb2d2.png)

**Comment by ckiss** [comment] 2015-09-21 07:28
@dberesford I've been trying to reproduce this but with no luck. I found an issue though, deleted dojos are still displayed here, which should not happen. I fixed it, though doesn't seem to be related to the issue you reported. Do you know what you did to make this happen?

**Comment by dberesford** [comment] 2015-09-21 07:33
to make it happen I look at my profile on the live zen site ;-)
However, it's correct now at the moment, I'm a member of two dojos. Feel
free to close this.

**Comment by ckiss** [comment] 2015-09-21 07:35
Seems to be back to normal now. Other issue I found can be tested later on after is merged. I'll update the label when it's deployed.

**Closed** 2015-09-28 11:57 UTC
Labels: bug, high priority
