### ISSUE TITLE
Language drop down does not have the current language selected by default

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1115] opened 2016-11-22 10:42 UTC
This means, as a result, you cannot switch from another language to English, since a change needs to occur in the selected value in order to trigger the language change

**Comment by asonder** [comment] 2017-02-20 02:38
I'd like to take a shot at this issue. This is my first time contributing to open source, and I'm excited to get involved.

**Comment by Wardormeur** [comment] 2017-02-20 05:32
Do you have the stack installed yet? If not, have a look at https://github.com/CoderDojo/cp-local-development .
For the next steps, I believe @DanielBrierton is having a better understanding of how it works than I do 😅

**Comment by asonder** [comment] 2017-02-20 15:12
Thanks for the info. I'm going to install the dev environment today, and when I'm working on the bug I'll check with @DanielBrierton if I have questions.

**Comment by DanielBrierton** [comment] 2017-02-21 22:28
@asonder Thanks for taking this, great to hear your stepping into the world of contributing to open source. 😄  If you have any issues getting set up, or on the bug itself, you can grab me on our Gitter: https://gitter.im/CoderDojo/community-platform or we can continue discussion here on this issue.

**Comment by asonder** [comment] 2017-02-22 02:19
Thanks @DanielBrierton ! I started to set things up yesterday, and I hope to have it done by the end of the week so that I can start working on the bug. I'll reach out if I have any issues.

**Comment by asonder** [comment] 2017-02-28 02:36
@DanielBrierton just letting you know that installing the dev environment is taking a little longer than expected, but I'm still committed to working on this bug!

**Comment by Wardormeur** [comment] 2017-05-19 09:05
@DanielBrierton @dmitry-portnoy gave it a try but couldn't reproduce
Hints? Could it has been a side effect of the double cookie issue we had previously

**Comment by Wardormeur** [comment] 2017-07-05 08:23
@DanielBrierton up !

**Comment by Wardormeur** [comment] 2018-03-17 12:20
Cannot reproduce anymore, either on old or new front-end.
Closing off!

**Closed by Wardormeur** 2018-03-17 12:20 UTC
Labels: beginner, bug, in progress
