### ISSUE TITLE
Event details render without translation

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/community-platform#990] opened 2016-06-30 02:43 UTC
Event grid in Dojo page shows Date and Type in english instead of spanish.
![error_traduccion_ficha_eventos](https://cloud.githubusercontent.com/assets/1916339/16475051/bc3a68d8-3e51-11e6-8982-2af3a1e15303.png)

We checked with Chrome and Firefox browser, both in Argentinian spanish.

**Comment by elnomade** [comment] 2016-06-30 02:46
Sample: https://zen.coderdojo.com/dojo/ar/cordoba-cordoba/cordoba-pezs

**Comment by adhorrig** [comment] 2016-06-30 08:20
Hey @elnomade. This specific lack of translation has been reported into this issue - https://github.com/CoderDojo/community-platform/issues/934 :smile. 

The above issue also contains other areas which are not translated.

Adam.

**Comment by Wardormeur** [comment] 2016-07-08 09:53
Duplicate of #934 https://cloud.githubusercontent.com/assets/564768/11919877/3136c19e-a75e-11e5-8a88-e54e658c4d4a.PNG

**Closed by Wardormeur** 2016-07-08 09:53 UTC
Labels: duplicate
