### ISSUE TITLE
Date changing after recurring Event saved as Draft

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#893] opened 2016-01-26 11:30 UTC
Once the event is saved the end date is changing when you go in to edit again.

Reported by Ross, Champion in North Parramatta in Australia. Unsure if timezones or otherwise that is causing this issue.

Video here > https://drive.google.com/drive/folders/0B1eLynE0aU3mbVRmYmtlOHdtcjg

**Comment by tangentfairy** [comment] 2016-01-26 12:10
Possibly related to https://github.com/CoderDojo/community-platform/issues/868 and local storage. Could be specific to drafts only. [Start by looking here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/controllers/dojo-event-form-controller.js#L5).

**Comment by Wardormeur** [comment] 2016-02-06 23:31
I had a quick look at it, it's very likely related . 
For a recurrent event from the 2016/02/07 to the 2016/02/29, the function dojo-event-form-controller#calculateDatesObj took as input for the last event
`Date 2016-02-28T05:00:00.000Z, Date 2016-02-29T13:00:00.000Z `
(which is already wrong) and returned
`  { startTime: Date 2016-02-28T06:00:00.000Z, endTime: Date 2016-02-28T14:00:00.000Z }` which is also wrong because this function seems to consider that the event can only occurs on 1 date (is it by design?)

**Comment by tangentfairy** [comment] 2016-02-08 08:57
@Wardormeur thanks - that will be helpful for @adhorrig who is currently fixing this issue while he is adding the timezone feature to events as part of https://github.com/CoderDojo/community-platform/issues/889

**Comment by Wardormeur** [comment] 2016-03-21 19:04
@adhorrig Can we close this ?

**Comment by adhorrig** [comment] 2016-03-22 07:42
@wardormeur still open, the fix is on one of my local branches - will
checkout today and submit pr

**Closed** 2016-03-25 09:56 UTC
Labels: bug, events, high priority
