### ISSUE TITLE
Filter Users as  a Champion 

### ISSUE THREAD

**Issue by Giustina** [CoderDojo/community-platform#698] opened 2015-09-28 15:24 UTC
On the manage users page, it would be useful to have the ability to search for a specific user by name or by user type e.g show all ninjas over 13. Currently all users are listed in random (non alphabetical order. This feature should be accessible by anyone with Dojo admin / ticketing permissions. 

![screen shot 2015-09-28 at 16 23 50](https://cloud.githubusercontent.com/assets/4377517/10139967/53ea0194-65fd-11e5-91d5-44ec7271286d.png)

G

**Comment by tangentfairy** [comment] 2015-09-28 15:33
:+1:

**Comment by tangentfairy** [comment] 2015-11-11 17:14
In this section it would be good to have a feature to export all users to CSV.

**Comment by tangentfairy** [comment] 2015-12-01 09:40
Sort users alphabetically also

**Comment by andresiglesias** [comment] 2016-01-23 16:47
So, then it would be: 
- Being able to filter users by name/user type
- Sort users by name (both in web and csv)

?

**Comment by tangentfairy** [comment] 2016-01-25 09:02
@andresiglesias Yes, both sorting functions, and then the csv would be generated based on the sorting currently on the page.

**Comment by tangentfairy** [comment] 2016-01-28 12:58
For more information on creating test data so you can see the manage users page, [see this doc](https://github.com/CoderDojo/community-platform/blob/master/creating-test-data.md). The main [readme file is here](https://github.com/CoderDojo/community-platform/blob/master/README.md). 

- The [manage users controller is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/controllers/manage-dojo-users-controller.js)
- The [template for this controller is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/manage-dojo-users.dust)
- You'll also need to take a look [at the users service](https://github.com/CoderDojo/cp-users-service/blob/master/users.js), the backend section of the system.

Let me know if you have any questions, usually around on the [Gitter](https://gitter.im/CoderDojo/community-platform?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)!

**Comment by Wardormeur** [comment] 2016-03-22 11:48
Done by @SlashmanX :+1:

**Comment by Wardormeur** [comment] 2016-04-03 15:34
Search implementation is unfinished as multipage search is not working as intended (ie:: no results are found for the next pages)

**Comment by Wardormeur** [comment] 2016-04-13 10:47
Fixed by @butlerx

**Closed by Wardormeur** 2016-04-13 10:47 UTC
Labels: backlog, dojo admin, hints provided, normal priority
