### ISSUE TITLE
Event description is not loaded when editing an event

### ISSUE THREAD

**Issue by alan-donnelly** [CoderDojo/community-platform#892] opened 2016-01-25 17:38 UTC
Steps to reproduce:
1. Create a new event
2. Remember to write something memorable in the Description field 
3. Save as Draft or Publish the event (not certain it happens in the Draft scenario)
4. Edit the event (My Dojos -> Manage under events -> Edit next to the event created in 1.)

Notice the Description field is empty.

**Comment by tangentfairy** [comment] 2016-01-25 18:34
Hi @alan-donnelly This is a duplicate of issue https://github.com/CoderDojo/community-platform/issues/868

Thanks for the report!

**Closed by tangentfairy** 2016-01-25 18:34 UTC
