### ISSUE TITLE
Issue with special characters in title bar 

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#815] opened 2015-11-27 14:08 UTC
Just put Portuguese up but it looks like there's an issue on the homepage with the special characters in the page title:

![screen shot 2015-11-27 at 14 07 33](https://cloud.githubusercontent.com/assets/1136491/11442831/56b62474-9510-11e5-9fb7-ae7b874a9d9a.png)

**Comment by josmas** [comment] 2015-12-13 10:28
@tangentfairy where are the languages files for non EN translations? I can only see en_US messages.po in all the workspace.

**Comment by tangentfairy** [comment] 2015-12-13 10:57
This is in CrowdIn and is automatically synced to production. We only store
the source language in the repository!

On Sunday, December 13, 2015, Jos <notifications@github.com> wrote:

> @tangentfairy <https://github.com/tangentfairy> where are the languages
> files for non EN translations? I can only see en_US messages.po in all the
> workspace.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/815#issuecomment-164245699>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by tangentfairy** [comment] 2015-12-18 10:53
To explain further on this, if you go to https://crowdin.com/project/zen-community-platform/pt-PT and log in you'll be able to download the messages.po file, and then put it in web/locale/pt_PT/messages.po

Then you just make sure you don't check it in. Might be worth us adding any folder but the source languages to the .gitignore file

**Comment by CianMclennan** [comment] 2016-01-22 20:25
I'm looking at this for the hackathon

**Comment by tangentfairy** [comment] 2016-01-22 20:29
@CianMclennan I think @josmas is looking at it!

**Comment by josmas** [comment] 2016-01-22 21:04
Yeah, we've talked about it; it's grand for the weekend, we can reevaluate tomorrow

**Comment by DanielBrierton** [comment] 2016-09-15 10:39
While I'm not sure what the fix was – it may have been a bug in a dependency, or maybe someone specifically fixed it and never closed the issue – but this is no longer an problem, so I'm going to close this issue.

**Closed by DanielBrierton** 2016-09-15 10:39 UTC
Labels: beginner, bug, high priority, hints provided, translations

**Comment by josmas** [comment] 2016-09-15 12:35
@DanielBrierton It may not be the case anymore, but I seem to recall that the problem occurred only when you are not logged in as a user. Some dependency that was not fully loaded or similar. It was tricky to reproduce because while on dev mode you are most likely logged in (and with no additional languages loaded). But might not be the case anymore.

**Comment by DanielBrierton** [comment] 2016-09-15 12:38
@josmas I've tested the example above both logged in and logged out, and it displays correctly. @Wardormeur thinks it might have been an update to ui-router as we recently updated all our dependencies to the latest.

**Comment by Wardormeur** [comment] 2016-09-15 12:47
All the deps are now loaded too (dependancies.json) and the behavior for both dashboard and init-master were merged. Multiple possible reasons !
