### ISSUE TITLE
Import users from CSV

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#811] opened 2015-11-24 10:40 UTC
Request from community member to be able to import users from csv (presumably from eventbrite). 

We'd need to have an explanation on what format to expect this in (DOB, email, name, etc).

Related to https://github.com/CoderDojo/community-platform/issues/698 and https://github.com/CoderDojo/community-platform/issues/810

**Comment by coderdojopv** [comment] 2016-02-18 15:09
We would like this feature too.
I think the format could be a CSV or whatever (eventbrite exports in excel and other formats, from excel you can output CSV or TXT or whatever)
We have hundreds of ninjas we cannot add them manually

**Comment by DanielBrierton** [comment] 2016-09-30 11:23
Closing as duplicate of #667 as our intention is to allow bulk invite through the UI, that would allow you to paste in the contents of a CSV file, or just a plain list of emails

**Closed by DanielBrierton** 2016-09-30 11:23 UTC
Labels: backlog, dojo admin, low priority
