### ISSUE TITLE
No cancellation confirmation email when cancelling ticket through link in email.

### ISSUE THREAD

**Issue by grabartley** [CoderDojo/community-platform#1200] opened 2017-05-24 14:43 UTC
When I cancel my ticket for an event through the cancel link in the confirmation email I received, I don't get an email confirming that the cancellation was successful.

**Comment by Wardormeur** [comment] 2017-06-13 17:18
@rosalanghammer Should this be a scenario ?

**Comment by rosalanghammer** [comment] 2017-06-15 17:19
Yes you should get a cancellation email when you cancel through email.

**Comment by Wardormeur** [comment] 2018-07-05 09:57
Duplicate of https://github.com/CoderDojo/community-platform/issues/944

**Closed by Wardormeur** 2018-07-05 09:57 UTC
