### ISSUE TITLE
Review all error messages

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#1149] opened 2017-02-17 21:21 UTC
Lots of unfriendly error messages to be reviewed when I get time (Q2 2017 ideally)

**Comment by Wardormeur** [comment] 2019-04-25 11:23
Closing, the issue is not helpful in the current format. This is taken care of on a rework basis, so that if a screen is being reworked, messaging will be as well.
Considering there is no specific message being targeted, the issue is too broad to be taken care of.

**Closed by Wardormeur** 2019-04-25 11:23 UTC
