### ISSUE TITLE
Waiting list not working when not all classes or streams are sold out.

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#957] opened 2016-05-05 08:38 UTC
Waiting list does not activate for a specific stream. e.g. If the 'Scratch' tickets are sold out but the 'Parent' tickets are not. This needs to be the case or the Champion must have the option to enable the waitlist for specific streams.

It must only trigger when all tickets are sold out but I have not tested if this works.

**Comment by DanielBrierton** [comment] 2017-04-10 13:12
Closing as a duplicate of #1068.

**Closed by DanielBrierton** 2017-04-10 13:12 UTC
Labels: duplicate, events, high priority, Value for users
