### ISSUE TITLE
When adding an O13 to a parent, email is optional, but password is mandatory

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1038] opened 2016-09-27 09:26 UTC

**Comment by Wardormeur** [comment] 2017-05-02 08:50
@DanielBrierton ping, status?

**Comment by Wardormeur** [comment] 2017-09-29 12:30
@DanielBrierton bump :)

**Comment by Wardormeur** [comment] 2018-03-17 11:59
Doesn't reproduce on /my-children and FTB will override the "quick-adding" children flow from the profile page.
Added to FTB flow to remove this once it's finished

**Comment by Wardormeur** [comment] 2018-11-26 00:36
FTB flow is published since .. Months. Closing as the original issue cannot be executed anymore (option removed)

**Closed by Wardormeur** 2018-11-26 00:36 UTC
Labels: in progress
