### ISSUE TITLE
Show upcoming events I am attending

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#706] opened 2015-10-01 13:44 UTC
On the events tab we show all the upcoming events for any Dojos you have joined.

It would be nice to show another section above this with "Events I am attending"

**Comment by tangentfairy** [comment] 2015-10-06 11:15
This could also go on the profile page, where members of the same Dojo can see this section.

**Comment by Wardormeur** [comment] 2017-09-29 12:49
Duplicate of https://github.com/CoderDojo/community-platform/issues/1046

**Closed by Wardormeur** 2017-09-29 12:49 UTC
Labels: events
