### ISSUE TITLE
Remove requirement for Over 13 email address

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#822] opened 2015-12-01 11:25 UTC
At the moment you cannot use the same email address for an O13 account.

i.e. a parent cannot use their email address for an O13 account. The issue with removing the unique email requirement is that then each O13 user will not be able to log in without a unique identifier.

I propose we use the alias field so that the O13 user can log in with an email _or_ an alias, and the alias must be unique. Then we can make the alias required and the email address optional.

Also, if you update a youth account with an existing email (after it has been created), the system lets you do this at the moment. Solving this issue would fix the problem where two accounts can have the same email/sign on detail too.

**Comment by josmas** [comment] 2015-12-09 16:46
Will everyone be able to log in with their alias, not just O13?

It seems that *aliases* are already unique (good!), so I might divide the work in here into two parts:
  - Login with alias (for everyone)
  - Remove restriction of email for O13

@tangentfairy thoughts?

**Comment by tangentfairy** [comment] 2015-12-09 18:22
Allowing login via alias for everyone is fine with me, sounds good!

On Wednesday, December 9, 2015, Jos <notifications@github.com> wrote:

> Will everyone be able to log in with their alias, not just O13?
>
> It seems that *aliases* are already unique (good!), so I might divide the
> work in here into two parts:
>
>    - Login with alias (for everyone)
>    - Remove restriction of email for O13
>
> @tangentfairy <https://github.com/tangentfairy> thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/822#issuecomment-163320082>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by josmas** [comment] 2015-12-10 19:44
Aliases seem to be kinda messed up. It's very easy to allow *nick* or *alias* login with ***seneca-user***, and it seems to work, but if a user *saves* their profile, the *alias* seems to overridden with the *email* data in the DB, and login works no more. But the *alias* field still appears as normal in the form; not sure how that value is cached, but it's all rather confusing. Might have to divide this into three parts instead of two, the additional one to fix **alias override**.

**Comment by josmas** [comment] 2015-12-11 16:03
Documenting here in case anyone else goes down the same rabbit hole...

Turns out that the *alias* in the profile is stored in the *cd_profiles* table, but the user information is stored in *sys_user*. There is no local storage interference here, it's just two different tables in the DB. I guess the two tables come from the fact that seneca-user is used for users, so it has its own table. The problem is that we want to use that *alias* field to log in, so saving a profile will need to write to two tables. I also guess this is why there's no way to change passwords within the application, only through an external reset password action (not from profile). This is really convoluted. Any advice/corrections welcome.

**Comment by tangentfairy** [comment] 2015-12-11 16:08
Agreed, that doesn't sound ideal! I think it would be better to just store the alias in the sys_user table, but would like to hear other opinions on this if possible!

There is a feature issue to [enable the updating of your password here](https://github.com/CoderDojo/community-platform/issues/432).

**Comment by josmas** [comment] 2015-12-11 16:16
Yes, but the only way I see to store the alias in sys_user is to do two writes, one to the profile table and one to the users table. BTW the *alias* field in seneca-user is called *nick* or *username*.

This may be a question for the seneca guys? @dberesford Is there a way to augment the seneca-user user object with data from the profile? I guess the answer is *nope*, otherwise it would have been that way in the first place instead of having two separate entities (user and profile)?

**Comment by Wardormeur** [comment] 2016-03-24 09:28
We're gonna remove the requirement in the first place for Parents adding children to have an email address.
Children won't be able to login until parents are adding the email address but it'll be less of a pain for parents to register their children

**Comment by Wardormeur** [comment] 2018-03-17 12:08
^ PR has been merged a year ago, closing off

**Closed by Wardormeur** 2018-03-17 12:08 UTC
Labels: high priority, in progress, profiles/users, request for comments
