### ISSUE TITLE
Usability improvement: show loading message instead of no data

### ISSUE THREAD

**Issue by FDelporte** [CoderDojo/community-platform#940] opened 2016-03-21 08:18 UTC
eg if you go to my dojo > users, you get the message you have no users, until you wait long enough when they appear.

so actually the initial message is wrong, it should be "loading data..." and after loading show the list or "no users" when there are none indeed.

to be reworked in every place where data loads after loading the page (users, events, my dojos, ...)

**Comment by Wardormeur** [comment] 2016-03-21 10:00
Yes, we'd like a spinner here to avoid confusion.
It's just a short matter of time ;)

**Comment by tangentfairy** [comment] 2016-03-21 20:08
I think this is a duplicate of https://github.com/CoderDojo/community-platform/issues/760 - there is actually a pull request for it here that is probably good to merge once it is tested and synced with master. https://github.com/CoderDojo/community-platform/issues/760

**Closed** 2016-03-21 20:09 UTC
Labels: beginner, enhancement, normal priority, up-for-grabs
