### ISSUE TITLE
Entering of address to be optional for all non-Champion users. 

### ISSUE THREAD

**Issue by LauraCDF** [CoderDojo/community-platform#733] opened 2015-10-12 16:26 UTC
Only Champions are required to share their address with us for verification purposes so this field should be removed from being required for all other users.

**Comment by tangentfairy** [comment] 2015-10-16 17:44
Duplicate of https://github.com/CoderDojo/community-platform/issues/737 so will close this one.

**Closed by tangentfairy** 2015-10-16 17:44 UTC
Labels: backlog, duplicate
