### ISSUE TITLE
Salesforce errors..

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#618] opened 2015-09-11 14:43 UTC
```
Details: { id: 'q0377e06szyg/jnszump1kzgx',
  gate: false,
  ungate: true,
  desc: 'cmd:save,role:entity',
  plugin: { name: 'salesforce-store', tag: 'GBP' },
  time: { start: 1441966395470, end: 1441966396569 },
  'orig$':
   { name: 'INVALID_FIELD_FOR_INSERT_UPDATE',
     errorCode: 'INVALID_FIELD_FOR_INSERT_UPDATE',
     fields: [ 'Name' ] },
  'message$': 'Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set.',
  message: 'Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set.',
  pattern: 'cmd:save,role:entity',
  instance: 'Seneca/0.6.4/qaqse2aaqkjj/1441795181396/7330/-' }

Stack:
    at Object.handle_response (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:86:15)
    at /opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/transport.js:569:16
    at done (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)```

```

and this one:

```
Message: seneca: Action cmd:save,role:entity failed: Required fields are missing: [LastName, Company].

Code: act_execute

Details: { id: 'zvfb9tqn8xow/te3xwcq077m6',
  gate: false,
  ungate: true,
  desc: 'cmd:save,role:entity',
  plugin: { name: 'salesforce-store', tag: 'GBP' },
  time: { start: 1441966803025, end: 1441966804093 },
  'orig$':
   { name: 'REQUIRED_FIELD_MISSING',
     errorCode: 'REQUIRED_FIELD_MISSING',
     fields: [ 'LastName', 'Company' ] },
  'message$': 'Required fields are missing: [LastName, Company]',
  message: 'Required fields are missing: [LastName, Company]',
  pattern: 'cmd:save,role:entity',
  instance: 'Seneca/0.6.4/qaqse2aaqkjj/1441795181396/7330/-' }

Stack:
    at Object.handle_response (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:86:15)
    at /opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/transport.js:569:16
    at done (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by daveymoran-nearform** [comment] 2015-09-21 14:14
there was an issue with the the user/dojo ids being mixed up on delete/verify. the INVALID_FIELD_FOR_INSERT_UPDATE error most likely was caused due to trying to save a value in the wrong object. this has now been fixed.

**Comment by daveymoran-nearform** [comment] 2015-09-21 14:16
the REQUIRED_FIELD_MISSING error was most likely caused by the same id issue mentioned above, trying to save a new object without the mandatory fields instead of updating and objects specific fields. this is also fixed now.

**Comment by daveymoran-nearform** [comment] 2015-09-21 14:17
will update the issues labels when the fix has been deployed to production server.

**Closed** 2015-09-22 16:22 UTC
Labels: bug, high priority, Ready For Testing
