### ISSUE TITLE
Salesforce not updating Lead Status

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#641] opened 2015-09-15 10:44 UTC
We came across this when we tried to set up an email alert.

If you look at the activity on the Hello World Foundation account https://eu2.salesforce.com/_ui/core/userprofile/UserProfilePage?tab=sfdc.ProfilePlatformFeed&u=005b0000000jOY6

There are a number of Dojos going from Step 4 to Step 7. Somehow we are not pinging Salesforce when the Dojo goes past 5. Dojo Listing Created.

This used to work, as if you scroll down that page you'll see a Dojo go from Step 5 to Step 7 on the 10th September.

Did we change something in the interim?

**Comment by daveymoran-nearform** [comment] 2015-09-18 08:23
confirmed, the saving of the dojo listing is not being saved to salesforce.

**Comment by daveymoran-nearform** [comment] 2015-09-18 16:36
fixed. will update labels when deployed.

**Comment by tangentfairy** [comment] 2015-09-21 14:56
CC @rosalanghammer

**Comment by tangentfairy** [comment] 2015-09-25 08:55
This is working now, but we seem to update some leads to step 5 a bit early. See some tests that @BenChapman created here https://eu2.salesforce.com/_ui/search/ui/UnifiedSearchResults?searchType=2&sen=00Q&sen=001&sen=005&str=sfdc

The Dojo listing is supposed to have a Lead Status of 5 _after_ they create the listing. Before that it will be on the previous step.

Also... The Lead Record Type is now incorrect. Here is a Lead that was just created https://eu2.salesforce.com/00Qb000000I65Gt

It has the Lead Record Type of Donation rather than Champion.

**Comment by daveymoran-nearform** [comment] 2015-09-28 10:41
i am unsure how the lead record type could be "donation", that value is assigned via a process environment variable which is set on users, dojos, and salesforce services. all three services have the correct (and same) lead type id.

**Comment by tangentfairy** [comment] 2015-09-28 10:46
Something has changed - all of the new Leads have the Donation record type - e.g. https://eu2.salesforce.com/00Qb000000IFLND

You can see it in this view I made here, if you sort by last modified date - https://eu2.salesforce.com/00Q?fcf=00Bb00000049zcd

Strangely it seems to have broken sometime in between 9th and 22nd of September - the last record to have the correct record type is this one (from the 9th) https://eu2.salesforce.com/00Qb000000HvY6t

The record type stopped working when the email field changed, so I think something was introduced there.

**Comment by daveymoran-nearform** [comment] 2015-09-28 10:48
I am unsure as to how that is happening as there is only one line of code in the entire system (dojos.js: updateSalesForceLead function) that sets the status to be "5. Dojo Listing Created" and that is called when saving the dojo listing. are these tests automated? or manual?

**Comment by daveymoran-nearform** [comment] 2015-09-28 11:17
@tangentfairy can you check the salesforce field level permissions for production account_record_type? new users are given a type of community instead of champion and it may be because some of the values are hidden. thanks

**Comment by daveymoran-nearform** [comment] 2015-09-28 11:30
some odd behaviour observed here, looks like old behavior from previous bugs have returned somehow. will have to investigate further.

**Comment by tangentfairy** [comment] 2015-09-28 14:07
I'm not sure if this is related. We seem to have a number of duplicate applications for one particular Champion: https://eu2.salesforce.com/_ui/search/ui/UnifiedSearchResults?str=Renato+Tamilio&sen=00Q#!/fen=00Q&initialViewMode=detail&str=Renato%20Tamilio

There is only one entry in the cd_dojoleads table so I'm not sure how Salesforce got in to this state.

**Comment by daveymoran-nearform** [comment] 2015-09-28 14:29
Both the above issues were down to a variable name change in the salesforce savelead method which wasnt merged. This means that every time the the lead is saved it was being saved as a new lead salesforce instead of updating the one lead. this is why the status updates would have seemed out of sequence. the lead record type is set in step 2 but after that it is not updated until the convert script and that is why the new lead was being created with the default record type, which happened to be "donation".

**Closed** 2015-10-16 18:40 UTC
Labels: bug, high priority
